<a href="https://colab.research.google.com/github/Shadoww002/PyTorch-Learning/blob/main/Chapter%200%20%E2%80%93%20PyTorch%20Fundamentals/Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
import torch
# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor


tensor([[0.0563, 0.5857, 0.8362, 0.4607, 0.7105, 0.0586, 0.7951],
        [0.3923, 0.2675, 0.8316, 0.1586, 0.6124, 0.3810, 0.3077],
        [0.5524, 0.7969, 0.9546, 0.4215, 0.2785, 0.6435, 0.4992],
        [0.6075, 0.1255, 0.2913, 0.6870, 0.2714, 0.3590, 0.8235],
        [0.4350, 0.8848, 0.8885, 0.3967, 0.8573, 0.1168, 0.9492],
        [0.4601, 0.4265, 0.5242, 0.9306, 0.1256, 0.0297, 0.9514],
        [0.1689, 0.8877, 0.2077, 0.7200, 0.6706, 0.1494, 0.4231]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
random_tensor_2 = torch.rand(1,7)
random_tensor_2


# Perform matrix multiplication
torch.matmul(random_tensor,random_tensor_2.T)


tensor([[1.6827],
        [1.5427],
        [2.1696],
        [1.6423],
        [2.3052],
        [1.5112],
        [1.7365]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
random_seed = 0 ;
torch.manual_seed(random_seed)
# Create two random tensors
random_1 = torch.rand(7,7)
random_2 = torch.rand(7,1)

# Matrix multiply tensors
torch.matmul(random_1,random_2)



tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU
torch.cuda.is_available()

random_seed = 1234
torch.cuda.manual_seed(random_seed)
# random = torch.rand(2,3)
# random , random.device


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [38]:
# Set random seed
# random_seed = 1234
torch.cuda.manual_seed(1234)

# Check for access to GPU
check = torch.cuda.is_available()

device = "cuda" if check else "cpu"

# Create two random tensors on GPU

random_a = torch.rand(2,3).to(device)

random_b = torch.rand(2,3).to(device)
random_a,random_b

(tensor([[0.0242, 0.6630, 0.9787],
         [0.1037, 0.3920, 0.6084]], device='cuda:0'),
 tensor([[0.0928, 0.0719, 0.8733],
         [0.3230, 0.7917, 0.5447]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [39]:
# Perform matmul on tensor_A and tensor_B
torch.matmul(random_a,random_b.T)

tensor([[0.9046, 1.0658],
        [0.5691, 0.6752]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [49]:
# Find max
print(f"Max in a :{torch.max(random_a)}")
print(f"Max in b :{random_b.max()}")


# Find min
print(f"Min in a :{torch.min(random_a)}")
print(f"Min in b :{random_b.min()}")


Max in a :0.9786772131919861
Max in b :0.8732667565345764
Min in a :0.024244964122772217
Min in b :0.07191967964172363


### 9. Find the maximum and minimum index values of the output of 7.

In [51]:
# Find arg max
print(f"Max in a is at :{torch.argmax(random_a)}")
print(f"Max in b is at :{random_b.argmax()}")

# Find arg min
print(f"Min in a is at  :{torch.argmin(random_a)}")
print(f"Min in b is at :{random_b.argmin()}")



Max in a is at :2
Max in b is at :2
Min in a is at  :0
Min in b is at :1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [53]:
# Set seed
torch.manual_seed(7)


# Create random tensor
random = torch.rand(1,1,1,10)


# Remove single dimensions
random_squeeze = torch.squeeze(random)


# Print out tensors and their shapes
print(f"{random} , shape : {random.shape}")
print(f"{random_squeeze} , shape : {random_squeeze.shape}")


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) , shape : torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) , shape : torch.Size([10])


In [54]:
## Finshed👍