<a href="https://colab.research.google.com/github/Shadoww002/PyTorch-Learning/blob/main/Chapter%200%20%E2%80%93%20PyTorch%20Fundamentals/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


**Understanding Tensors**

In [57]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [58]:
scalar.ndim

0

In [59]:
scalar.shape

torch.Size([])

In [60]:
#vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [61]:
vector.ndim

1

In [62]:
vector.shape

torch.Size([2])

In [63]:
#Matrix
MATRIX = torch.tensor([[1,1],[2,3]])
MATRIX

tensor([[1, 1],
        [2, 3]])

In [64]:
MATRIX.ndim

2

In [65]:
MATRIX.shape

torch.Size([2, 2])

In [66]:
#tensor
TENSOR = torch.tensor([[[[1,2],[2,3],[3,4],[4,5]]]])
TENSOR

tensor([[[[1, 2],
          [2, 3],
          [3, 4],
          [4, 5]]]])

In [67]:
TENSOR.ndim

4

In [68]:
TENSOR.shape

torch.Size([1, 1, 4, 2])

In [69]:
###RANDOM TENSORS


In [70]:
random_tensor = torch.rand(1,4,5)
random_tensor

tensor([[[0.6720, 0.4555, 0.3375, 0.6818, 0.1797],
         [0.0661, 0.6565, 0.3457, 0.8041, 0.9718],
         [0.4135, 0.6178, 0.8723, 0.5311, 0.3906],
         [0.3886, 0.4847, 0.0147, 0.9385, 0.7864]]])

In [71]:
random_tensor.shape

torch.Size([1, 4, 5])

In [72]:
random_tensor.ndim

3

In [73]:
random_image_size_tensor = torch.rand(111,111,3)

In [74]:
random_image_size_tensor.ndim

3

In [75]:
random_image_size_tensor.shape

torch.Size([111, 111, 3])

In [76]:
### Zeros and Ones Tensor
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [77]:
ones = torch.ones(2,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [78]:
zeros.dtype ##default dtype

torch.float32

In [79]:
## Range of Tensor and tensor -LIke

In [80]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
ten_zeroes = torch.zeros_like(input=(random_tensor))
ten_zeroes

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [82]:
## tensor datatype , device and gradient

In [83]:
tensor_32float = torch.tensor([1,2,3,4,4],
                              dtype=torch.float32,
                              device=None,
                              requires_grad=False)

tensor_32float

tensor([1., 2., 3., 4., 4.])

In [84]:
tensor_32float.dtype

torch.float32

In [85]:
tensor_16float = tensor_32float.type(torch.float16)
tensor_16float

tensor([1., 2., 3., 4., 4.], dtype=torch.float16)

In [86]:
## Tensor INFO
some_tensor = torch.rand(4,5)
print(some_tensor)
print(f"Dtype : {some_tensor.dtype}")
print(f"shape : {some_tensor.shape}")
print(f"Device : {some_tensor.device}")


tensor([[0.6545, 0.0531, 0.4581, 0.1242, 0.4328],
        [0.6996, 0.7184, 0.6233, 0.3691, 0.7428],
        [0.3863, 0.4280, 0.1545, 0.4799, 0.3038],
        [0.4179, 0.2064, 0.2623, 0.5643, 0.8643]])
Dtype : torch.float32
shape : torch.Size([4, 5])
Device : cpu


In [87]:
## Manipulating Tensors i.e Opertions on Tensors

In [88]:
tensor = torch.tensor([1,2,3,4])
tensor

tensor([1, 2, 3, 4])

In [89]:
tensor + 100

tensor([101, 102, 103, 104])

In [90]:
tensor - 100

tensor([-99, -98, -97, -96])

In [91]:
tensor * 100

tensor([100, 200, 300, 400])

In [92]:
## Matrix Multiplication

In [93]:
torch.matmul(torch.rand(3,4),torch.rand(4,5))

tensor([[1.0774, 1.8309, 1.5731, 1.1078, 1.6770],
        [0.6482, 1.3048, 1.3110, 0.8235, 1.3072],
        [0.7043, 1.3830, 0.4694, 0.7755, 0.8353]])