<a href="https://colab.research.google.com/github/Shadoww002/PyTorch-Learning/blob/main/Chapter%200%20%E2%80%93%20PyTorch%20Fundamentals/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


**Understanding Tensors**

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
#vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[1,1],[2,3]])
MATRIX

tensor([[1, 1],
        [2, 3]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#tensor
TENSOR = torch.tensor([[[[1,2],[2,3],[3,4],[4,5]]]])
TENSOR

tensor([[[[1, 2],
          [2, 3],
          [3, 4],
          [4, 5]]]])

In [12]:
TENSOR.ndim

4

In [13]:
TENSOR.shape

torch.Size([1, 1, 4, 2])

In [14]:
###RANDOM TENSORS


In [15]:
random_tensor = torch.rand(1,4,5)
random_tensor

tensor([[[0.8234, 0.4255, 0.5700, 0.8092, 0.5330],
         [0.4417, 0.3761, 0.9888, 0.7998, 0.3277],
         [0.8797, 0.3191, 0.5231, 0.4996, 0.0300],
         [0.6395, 0.5248, 0.1747, 0.2784, 0.6140]]])

In [16]:
random_tensor.shape

torch.Size([1, 4, 5])

In [17]:
random_tensor.ndim

3

In [18]:
random_image_size_tensor = torch.rand(111,111,3)

In [19]:
random_image_size_tensor.ndim

3

In [20]:
random_image_size_tensor.shape

torch.Size([111, 111, 3])

In [21]:
### Zeros and Ones Tensor
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(2,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [23]:
zeros.dtype ##default dtype

torch.float32

In [24]:
## Range of Tensor and tensor -LIke

In [25]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
ten_zeroes = torch.zeros_like(input=(random_tensor))
ten_zeroes

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [27]:
## tensor datatype , device and gradient

In [28]:
tensor_32float = torch.tensor([1,2,3,4,4],
                              dtype=torch.float32,
                              device=None,
                              requires_grad=False)

tensor_32float

tensor([1., 2., 3., 4., 4.])

In [29]:
tensor_32float.dtype

torch.float32

In [30]:
tensor_16float = tensor_32float.type(torch.float16)
tensor_16float

tensor([1., 2., 3., 4., 4.], dtype=torch.float16)

In [31]:
## Tensor INFO
some_tensor = torch.rand(4,5)
print(some_tensor)
print(f"Dtype : {some_tensor.dtype}")
print(f"shape : {some_tensor.shape}")
print(f"Device : {some_tensor.device}")


tensor([[0.8786, 0.7485, 0.0757, 0.3577, 0.8967],
        [0.5103, 0.7702, 0.9055, 0.4259, 0.4527],
        [0.6184, 0.4285, 0.1516, 0.7241, 0.0858],
        [0.9666, 0.9676, 0.5064, 0.0036, 0.9763]])
Dtype : torch.float32
shape : torch.Size([4, 5])
Device : cpu


In [32]:
## Manipulating Tensors i.e Opertions on Tensors

In [33]:
tensor = torch.tensor([1,2,3,4])
tensor

tensor([1, 2, 3, 4])

In [34]:
tensor + 100

tensor([101, 102, 103, 104])

In [35]:
tensor - 100

tensor([-99, -98, -97, -96])

In [36]:
tensor * 100

tensor([100, 200, 300, 400])

In [37]:
## Matrix Multiplication

In [38]:
torch.matmul(torch.rand(3,4),torch.rand(4,5))

tensor([[0.7024, 1.2886, 0.7514, 1.2069, 1.1967],
        [0.5615, 1.2224, 0.5271, 1.0121, 1.1410],
        [0.5750, 1.5833, 0.6003, 1.1923, 1.4300]])

In [39]:
## Tensor Aggregation

In [40]:
x = torch.arange(1,100,8)
x , x.dtype

(tensor([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97]), torch.int64)

In [41]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [42]:
torch.max(x) , x.max()

(tensor(97), tensor(97))

In [43]:
torch.mean(x.type(torch.float32)) , x.type(torch.float16).mean()

(tensor(49.), tensor(49., dtype=torch.float16))

In [44]:
x.sum()

tensor(637)

In [45]:
## Finding Position min and max

In [46]:
x.argmin() , x[0]

(tensor(0), tensor(1))

In [47]:
x.argmax() ,x[12]

(tensor(12), tensor(97))

In [48]:
## Reshaping , Stacking , Squeezing and UnSqueezing

In [49]:
x = torch.arange(1,10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [50]:
x_reshaped = x.reshape((1,9))
x_reshaped , x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [51]:
x_reshaped = x.reshape(9,1)
x_reshaped , x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [52]:
z = x.view(1,9)
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
z[:,0] = 10
z

tensor([[10,  2,  3,  4,  5,  6,  7,  8,  9]])

In [54]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [55]:
x_stacked = torch.stack([x,x,x,x,x,x] , dim=0)
x_stacked

tensor([[10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9]])

In [56]:
x_stacked = torch.stack([x,x,x,x,x,x] , dim=1)
x_stacked

tensor([[10, 10, 10, 10, 10, 10],
        [ 2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8,  8],
        [ 9,  9,  9,  9,  9,  9]])

In [57]:
x_squeezed = x_reshaped.squeeze()
x_squeezed , x_squeezed.shape

(tensor([10,  2,  3,  4,  5,  6,  7,  8,  9]), torch.Size([9]))

In [58]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed , x_unsqueezed.shape

(tensor([[10,  2,  3,  4,  5,  6,  7,  8,  9]]), torch.Size([1, 9]))

In [59]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
x_unsqueezed , x_unsqueezed.shape

(tensor([[10],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9]]),
 torch.Size([9, 1]))

In [60]:
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [61]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [62]:
### PyTorch Tensors and NumPY

In [63]:
# Numpy arr to Tensors

In [64]:
array = np.arange(1.0 , 10.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [65]:
array.dtype

dtype('float64')

In [66]:
# Tensor to Numpy Array

In [67]:
tensor = torch.ones(10)
numpy_array = tensor.numpy()
tensor , numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
## Reproducibility ans Random Seed Concept in PyTorch

In [69]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8684, 0.5435, 0.3000, 0.7498],
        [0.1326, 0.3639, 0.0365, 0.0406],
        [0.5506, 0.6376, 0.1370, 0.0382]])
tensor([[0.7154, 0.9685, 0.3148, 0.2908],
        [0.0416, 0.6313, 0.9668, 0.7973],
        [0.9111, 0.6877, 0.9740, 0.5755]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [70]:
random_seed = 10000
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.6404, 0.0649, 0.9975, 0.0407],
        [0.3505, 0.6598, 0.1372, 0.6529],
        [0.7072, 0.4786, 0.9184, 0.5454]])
tensor([[0.6404, 0.0649, 0.9975, 0.0407],
        [0.3505, 0.6598, 0.1372, 0.6529],
        [0.7072, 0.4786, 0.9184, 0.5454]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [71]:
## Running Tensors on GPU's

In [72]:
!nvidia-smi

Tue Jul  1 11:44:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   57C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [73]:
import torch
torch.cuda.is_available()

True

In [74]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [75]:
tensor = torch.tensor([1,2,3,4,5])
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [76]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu , tensor_on_cpu.device

(array([1, 2, 3, 4, 5]), 'cpu')