<a href="https://colab.research.google.com/github/Shadoww002/PyTorch-Learning/blob/main/Chapter%200%20%E2%80%93%20PyTorch%20Fundamentals/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


**Understanding Tensors**

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
#vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix
MATRIX = torch.tensor([[1,1],[2,3]])
MATRIX

tensor([[1, 1],
        [2, 3]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#tensor
TENSOR = torch.tensor([[[[1,2],[2,3],[3,4],[4,5]]]])
TENSOR

tensor([[[[1, 2],
          [2, 3],
          [3, 4],
          [4, 5]]]])

In [14]:
TENSOR.ndim

4

In [15]:
TENSOR.shape

torch.Size([1, 1, 4, 2])

In [16]:
###RANDOM TENSORS


In [17]:
random_tensor = torch.rand(1,4,5)
random_tensor

tensor([[[0.9561, 0.3429, 0.4197, 0.5939, 0.9318],
         [0.3273, 0.2700, 0.4178, 0.1480, 0.1518],
         [0.9529, 0.1084, 0.7350, 0.6649, 0.9728],
         [0.1616, 0.7239, 0.5693, 0.7104, 0.9338]]])

In [18]:
random_tensor.shape

torch.Size([1, 4, 5])

In [19]:
random_tensor.ndim

3

In [20]:
random_image_size_tensor = torch.rand(111,111,3)

In [21]:
random_image_size_tensor.ndim

3

In [22]:
random_image_size_tensor.shape

torch.Size([111, 111, 3])

In [23]:
### Zeros and Ones Tensor
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(2,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [25]:
zeros.dtype ##default dtype

torch.float32

In [26]:
## Range of Tensor and tensor -LIke

In [27]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ten_zeroes = torch.zeros_like(input=(random_tensor))
ten_zeroes

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [29]:
## tensor datatype , device and gradient

In [30]:
tensor_32float = torch.tensor([1,2,3,4,4],
                              dtype=torch.float32,
                              device=None,
                              requires_grad=False)

tensor_32float

tensor([1., 2., 3., 4., 4.])

In [31]:
tensor_32float.dtype

torch.float32

In [32]:
tensor_16float = tensor_32float.type(torch.float16)
tensor_16float

tensor([1., 2., 3., 4., 4.], dtype=torch.float16)

In [33]:
## Tensor INFO
some_tensor = torch.rand(4,5)
print(some_tensor)
print(f"Dtype : {some_tensor.dtype}")
print(f"shape : {some_tensor.shape}")
print(f"Device : {some_tensor.device}")


tensor([[0.0795, 0.3823, 0.3968, 0.1794, 0.4615],
        [0.7593, 0.1097, 0.8115, 0.6611, 0.8978],
        [0.6562, 0.7884, 0.4531, 0.7711, 0.8217],
        [0.4312, 0.4844, 0.1495, 0.6160, 0.9837]])
Dtype : torch.float32
shape : torch.Size([4, 5])
Device : cpu


In [34]:
## Manipulating Tensors i.e Opertions on Tensors

In [35]:
tensor = torch.tensor([1,2,3,4])
tensor

tensor([1, 2, 3, 4])

In [36]:
tensor + 100

tensor([101, 102, 103, 104])

In [37]:
tensor - 100

tensor([-99, -98, -97, -96])

In [38]:
tensor * 100

tensor([100, 200, 300, 400])

In [39]:
## Matrix Multiplication

In [40]:
torch.matmul(torch.rand(3,4),torch.rand(4,5))

tensor([[0.5953, 0.8789, 0.8563, 1.5572, 0.7720],
        [0.6772, 1.1280, 1.0948, 1.9327, 0.8170],
        [0.3076, 0.9499, 0.6925, 1.3954, 0.7344]])

In [51]:
## Tensor Aggregation

In [52]:
x = torch.arange(1,100,8)
x , x.dtype

(tensor([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97]), torch.int64)

In [44]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [45]:
torch.max(x) , x.max()

(tensor(97), tensor(97))

In [49]:
torch.mean(x.type(torch.float32)) , x.type(torch.float16).mean()

(tensor(49.), tensor(49., dtype=torch.float16))

In [50]:
x.sum()

tensor(637)

In [53]:
## Finding Position min and max

In [56]:
x.argmin() , x[0]

(tensor(0), tensor(1))

In [57]:
x.argmax() ,x[12]

(tensor(12), tensor(97))

In [58]:
## Reshaping , Stacking , Squeezing and UnSqueezing

In [93]:
x = torch.arange(1,10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [94]:
x_reshaped = x.reshape((1,9))
x_reshaped , x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [95]:
x_reshaped = x.reshape(9,1)
x_reshaped , x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [96]:
z = x.view(1,9)
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [97]:
z[:,0] = 10
z

tensor([[10,  2,  3,  4,  5,  6,  7,  8,  9]])

In [98]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [99]:
x_stacked = torch.stack([x,x,x,x,x,x] , dim=0)
x_stacked

tensor([[10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9],
        [10,  2,  3,  4,  5,  6,  7,  8,  9]])

In [100]:
x_stacked = torch.stack([x,x,x,x,x,x] , dim=1)
x_stacked

tensor([[10, 10, 10, 10, 10, 10],
        [ 2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8,  8],
        [ 9,  9,  9,  9,  9,  9]])

In [112]:
x_squeezed = x_reshaped.squeeze()
x_squeezed , x_squeezed.shape|

(tensor([10,  2,  3,  4,  5,  6,  7,  8,  9]), torch.Size([9]))

In [115]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed , x_unsqueezed.shape

(tensor([[10,  2,  3,  4,  5,  6,  7,  8,  9]]), torch.Size([1, 9]))

In [118]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
x_unsqueezed , x_unsqueezed.shape

(tensor([[10],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9]]),
 torch.Size([9, 1]))

In [120]:
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [123]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])